import os
from groq import Groq
from fpdf import FPDF
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


class AttendanceAI:
    def __init__(self):
        self.client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
        self.model = "llama-3.1-8b-instant"

    def generate_ai_summary(self, attendance_data, all_students=None):
        """
        attendance_data: list of tuples (name, date, time)
        all_students: optional list of all registered student names
        """
        student_info = ""
        if all_students:
            present_names = list(set(r[0] for r in attendance_data))
            absent_names = [s for s in all_students if s not in present_names]
            student_info = f"""
Total Registered Students: {len(all_students)}
Present Today: {len(present_names)} — {', '.join(present_names)}
Absent Today: {len(absent_names)} — {', '.join(absent_names) if absent_names else 'None'}
"""

        prompt = f"""You are an AI assistant for PSNA College of Engineering & Technology, Dindigul.
Analyze this attendance data for {datetime.now().strftime('%Y-%m-%d')}:

{student_info}

Raw Attendance Logs:
{attendance_data}

Provide a professional report with:
1. Summary: Total present vs absent count
2. Absentee List with names
3. Late arrivals (anyone marked after 9:00 AM for period 1)
4. Continuous absentee warning (if you can detect patterns)
5. Recommendations for the instructor

Keep it concise and professional. Use bullet points."""

        completion = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
        )
        return completion.choices[0].message.content

    def create_pdf_report(self, ai_summary, attendance_list):
        """Creates a professional PDF report and returns the file path."""
        pdf = FPDF()
        pdf.add_page()

        # Header
        pdf.set_font("Arial", "B", 18)
        pdf.cell(0, 12, "PSNA College of Engineering & Technology", ln=True, align="C")
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 6, "Department of Computer Science and Engineering", ln=True, align="C")
        pdf.ln(4)

        # Title
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Smart Attendance - AI Daily Report", ln=True, align="C")
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %I:%M %p')}", ln=True, align="C")
        pdf.ln(8)

        # AI Summary
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "AI Analysis", ln=True)
        pdf.set_draw_color(73, 214, 255)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)
        pdf.set_font("Arial", "", 10)

        # Handle encoding for the summary text
        safe_summary = ai_summary.encode("latin-1", "replace").decode("latin-1")
        pdf.multi_cell(0, 5, safe_summary)
        pdf.ln(8)

        # Attendance Table
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Attendance Log", ln=True)
        pdf.set_draw_color(73, 214, 255)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

        # Table Header
        pdf.set_font("Arial", "B", 10)
        pdf.set_fill_color(13, 33, 49)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(70, 8, "Name", 1, 0, "C", True)
        pdf.cell(60, 8, "Date", 1, 0, "C", True)
        pdf.cell(60, 8, "Time", 1, 1, "C", True)

        # Table Rows
        pdf.set_font("Arial", "", 9)
        pdf.set_text_color(0, 0, 0)
        for i, record in enumerate(attendance_list):
            fill = i % 2 == 0
            if fill:
                pdf.set_fill_color(240, 248, 255)
            pdf.cell(70, 7, str(record[0]), 1, 0, "L", fill)
            pdf.cell(60, 7, str(record[1]), 1, 0, "C", fill)
            pdf.cell(60, 7, str(record[2]), 1, 1, "C", fill)

        # Footer
        pdf.ln(10)
        pdf.set_font("Arial", "I", 8)
        pdf.cell(0, 5, "Generated by Smart Attendance System | Batch 14 | Guide: Ms. R. Abarnaswara", ln=True, align="C")

        # Save
        report_dir = "reports"
        os.makedirs(report_dir, exist_ok=True)
        filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(report_dir, filename)
        pdf.output(filepath)
        return filepath

    def chat_with_attendance(self, query, context_data, all_students=None):
        """Chat interface for teachers to query attendance data."""
        student_info = ""
        if all_students:
            present_names = list(set(r[0] for r in context_data)) if context_data else []
            absent_names = [s for s in all_students if s not in present_names]
            student_info = f"""
Registered Students: {', '.join(all_students)}
Present Today: {', '.join(present_names) if present_names else 'None yet'}
Absent Today: {', '.join(absent_names) if absent_names else 'None'}
"""

        prompt = f"""You are a friendly AI Assistant for PSNA College Smart Attendance System.
You help teachers manage attendance. Be helpful and concise.

Context — Today's Attendance Data:
{student_info}
Raw Records: {context_data}

Teacher's Question: {query}

Answer clearly. If unsure, say so."""

        completion = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
        )
        return completion.choices[0].message.content
